version: '3'
services:
  front-stag:
    container_name: front-stag
    image: nginx:1.12
    environment:
      BACK_HOST: ${BACK_HOST}
      BACK_PORT: ${BACK_PORT}
    volumes:
      - ../../dist:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"