version: '3'
services:
  front-prod:
    container_name: front-prod
    image: nginx:1.12
    volumes:
      - /home/reg/${{ github.event.repository.name }}_prod/dist/:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"