version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    restart: on-failure:10
    build: ./
    networks:
      - application-prod-network
      - application-stag-network
    ports:
      - 81:81

networks:
  application-prod-network:
    external:
      name: front-prod_default
  application-stag-network:
    external:
      name: front-stag_default
