# https://www.cloudbooklet.com/how-to-install-nginx-and-lets-encrypt-with-docker-ubuntu-20-04/

version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    restart: always
    build: ./
    networks:
      - application-prod-network
      - application-stag-network
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/letsencrypt/data:/var/www/certbot
      - /etc/letsencrypt/live/tcas.it.kmitl.ac.th/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/tcas.it.kmitl.ac.th/privkey.pem:/etc/nginx/ssl/privkey.pem
  certbot:
    container_name: 'certbot'
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email dev.vasin@gmail.com --agree-tos --no-eff-email -d tcas.it.kmitl.ac.th -d
    volumes:
      - /etc/letsencrypt/conf:/etc/letsencrypt
      - /etc/letsencrypt/logs:/var/log/letsencrypt
      - /etc/letsencrypt/data:/var/www/certbot
networks:
  application-prod-network:
    external:
      name: front-prod_default
  application-stag-network:
    external:
      name: front-stag_default
