version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    restart: always
    build: ./
    networks:
      - application-prod-network
      - application-stag-network
    ports:
      - 81:81
      - 8080:8080

networks:
  application-prod-network:
    external:
      name: front-prod_default
  application-stag-network:
    external:
      name: front-stag_default
