name: Deploy Staging Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: dev

      # Setup node with pnpm
      - name: Setup node
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 4.11.1

      # Install dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Build static
      - name: Build static
        run: pnpm run build
        env:
          NODE_ENV: staging

      # Copy project
      - name: Copy project
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key : ${{ secrets.SERVER_KEY }}
        source: ./
        target: ./${{ github.event.repository.name }}
        rm: true

      # Deploy project
      - name: Deploy project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          export BACK_HOST=${{ secrets.STAG_FRONT_HOST }}
          export BACK_PORT=${{ secrets.STAG_FRONT_PORT }}
          cd $home/${{ github.event.repository.name }}/nginx/font-stag
          docker-compose up -d --no-deps
          cd ../reverse-proxy
          docker-compose up -d --build
